### ISSUE TITLE
See also parser for ~/.mylogin.cnf

### ISSUE THREAD

**Issue by dolmen** [sjmudd/mysql_defaults_file#5]
See also those packages:
* [github.com/dolmen-go/mylogin](https://github.com/dolmen-go/mylogin)
* [github.com/dolmen-go/mylogin-driver](https://github.com/dolmen-go/mylogin-driver)

**Comment by sjmudd** [comment]
Thanks for the comment.
I don't use the mylogin format.

I have taken the suggestion to simplify usage by creating a function `Open()` which just takes the defaults-file name and optional database name.
